HRSystem/Models/SampleKey.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRSystem.Models
{
    public class SampleKey : Entity
    {
        public string Value { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
    }
}

HRSystem/ViewModels/SampleFormViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using HRSystem.Models;
using Microsoft.AspNetCore.Http;

namespace HRSystem.ViewModels
{
    public class SampleFormViewModel
    {
        [Required(ErrorMessage = "Введите название ceртификата")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Выберите файл")]
        public IFormFile SampleFile { get; set; }
        



    }
}

HRSystem/Controllers/SampleFormController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HRSystem.Models;
using HRSystem.Repositories;
using HRSystem.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HRSystem.Controllers
{
    public class SampleFormController : Controller
    {
        private readonly ISampleFormRepository sampleRepository;
        private readonly IHostingEnvironment environment;
        private readonly ISamoleKeyRepository samoleKeyRepository;
        private readonly ISampleFormRepository sampleFormRepository;

        public SampleFormController(ISampleFormRepository sampleRepository, IHostingEnvironment environment, ISamoleKeyRepository samoleKeyRepository, ISampleFormRepository sampleFormRepository)
        {
            this.sampleRepository = sampleRepository;
            this.environment = environment;
            this.samoleKeyRepository = samoleKeyRepository;
            this.sampleFormRepository = sampleFormRepository;
        }

        public IActionResult Index()
        {
            List<SampleForm> samples = sampleRepository.GetAllEntities().ToList();
            return View(samples);
        }

        public IActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult Create(SampleFormViewModel model)
        {
            sampleRepository.AddSample(model);
            return RedirectToAction("Index");
        }

        public IActionResult Info(int id)
        {
            SampleForm sample = sampleRepository.GetEntityById(id);
            string type = sample.Path.Split(".").Last();
            string sourceFile = Path.Combine(environment.WebRootPath, sample.Path);
            return PhysicalFile(sourceFile, $"application/{type}", sample.Name + $".{type}");
        }

        public IActionResult EmployeerSample(int sampleId, int employeerId)
        {
            SampleForm sample = sampleRepository.GetEntityById(sampleId);
            string type = sample.Path.Split(".").Last();
            string path;
            if (type.Equals("txt"))
            {
                path = sampleRepository.GetEmployeerSampleTxt(sampleId, employeerId);
            }
            else
            {
                path = sampleRepository.GetEmployeerSampleDocx(sampleId, employeerId);
            }
            return PhysicalFile(path, $"application/{type}", sample.Name + $".{type}");
        }

        [HttpPost]
        public string Delete(int sampleId)
        {
            sampleRepository.DeleteSample(sampleId);
            return JsonConvert.SerializeObject(true,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        public IActionResult SampleKeys()
        {
            List<SampleKey> sampleKeys = samoleKeyRepository.GetAllEntities().ToList();
            return PartialView(sampleKeys);
        }

        public IActionResult EditKey(int id)
        {
            SampleKey sampleKey = samoleKeyRepository.GetEntityById(id);
            return PartialView(sampleKey);
        }
        [HttpPost]
        public IActionResult EditKey(SampleKey model)
        {
            SampleKey sampleKey = samoleKeyRepository.GetEntityById(model.Id);
            sampleFormRepository.UpdateDocx(sampleKey.Key, model.Key);
            sampleKey.Key = model.Key;
            samoleKeyRepository.Update(sampleKey);
            return RedirectToAction("AdminSettings", "Home", new { type = "SampleKeys" });
        }
    }
}

HRSystem/Views/SampleForm/Create.cshtml
@model HRSystem.ViewModels.SampleFormViewModel

<div class="row ">
    <div class="col-md-12">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SampleFile" class="control-label">Файл</label>
                <input class="form-control" type="file" name="SampleFile" accept=".txt, .docx" />
                <span asp-validation-for="SampleFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@Html.Partial("_ValidationScriptsPartial")

HRSystem/Views/SampleForm/EditKey.cshtml
@model HRSystem.Models.SampleKey

<h4>Изменить ключ</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditKey" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Key" class="control-label">Ключ</label>
                <input asp-for="Key" class="form-control" />
                <span asp-validation-for="Key" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>



<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

HRSystem/Views/SampleForm/Index.cshtml
@model IEnumerable<HRSystem.Models.SampleForm>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Шаблоны</h1>

<div class="row">
    <div class="btn-group col-md-push-10  col-md-2">
        <button class="btn btn-default btn-block" onclick="createSample()">Добавить</button>
    </div>
</div>
<br />
<table  class="table table-striped table-bordered text-center">
    <thead>
    <tr>
        <th>Название</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var sample in Model)
    {
        <tr id="sample_@sample.Id">
            <td><a asp-action="Info" asp-route-id="@sample.Id">@sample.Name</a>  <a href="#ConfirmSample_@sample.Id" data-toggle="modal" class="pull-right"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
        <div class="modal" tabindex="-1" role="dialog" id="ConfirmSample_@sample.Id">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                    <div class="modal-body" style="margin: 10px">
                        <p> Действительно хотите удалить @sample.Name  ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" onclick="deleteSample(@sample.Id)" data-dismiss="modal">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                    </div>
                </div>
            </div>
        </div>
    }
        
    </tbody>
</table>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="modalResult">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Добавить Шаблон</h4>
            </div>
            <div class="modal-body" id="updateContent">

            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        function createSample() {
            $("#updateContent").load('@Url.Action("Create")');
            $("#myModal").modal();
        }

        function deleteSample(sampleId) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Delete","SampleForm")',
                data: { 'sampleId': sampleId},
                success: function () {
                    $('#sample_' + sampleId).hide();
                },
                error: function() {
                    alert("There was error uploading files!");
                }
            });
        }
    </script>
}

HRSystem/Views/SampleForm/SampleKeys.cshtml
@model IEnumerable<HRSystem.Models.SampleKey>


@{
    ViewData["Title"] = "Index";
}

<h1>Ключи</h1>

<br />
<table id="keyTable" class="table table-striped table-bordered text-center ">
    <thead>
    <tr>
        <th>Значение</th>
        <th>Ключ</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var key in Model)
    {
        <tr>
            <td>@key.Name</td>
            <td>$$@key.Key$$ <a href="#" class="pull-right" onclick="edit('SampleKey', '@key.Id')"><i class="fas fa-edit"></i></a></td>
        </tr>
    }
    </tbody>
</table>
@Html.Partial("_ValidationScriptsPartial")