HRSystem/Models/Employeer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HRSystem.Models
{
    public class Employeer : Entity
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string LastName { get; set; }
        public DateTime BirthdayDate { get; set; }
        
        public string PassportINN { get; set; }
        public DateTime PassportDateIn { get; set; }
        public DateTime PassportDateOut { get; set; }
        public string ByWhomGiven { get; set; }
        public string EmployeePhoto { get; set; }

        public bool isGender { get; set; }
        public bool isMilitaryService { get; set; }
        
        public bool isMarried { get; set; }
        
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public  string IdForPersonal { get; set; }
        
        public string Status { get; set; }
        public bool Notification { get; set; }
        

        [ForeignKey("Department")]
        public int DepartmentId { get; set; }
        public Department Department { get; set; }

        [ForeignKey("Position")]
        public int PositionId { get; set; }
        public Position Position { get; set; }


        public string History { get; set; }
    }
}

HRSystem/ViewModels/EmployeerViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using HRSystem.Models;
using Microsoft.AspNetCore.Http;

namespace HRSystem.ViewModels
{
    public class EmployeerViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Введите имя")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Введите фамилию")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Введите отчество")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Введите год рождения")]
        public DateTime BirthdayDate { get; set; }

        //public List<RelativeViewModel> Relations { get; set; }
        [Required(ErrorMessage = "Введите ФИО родственника")]
        public List<string> RelName { get; set; }
        [Required(ErrorMessage = "Введите статус родсвенника")]
        public List<string> RelType { get; set; }
        [Required(ErrorMessage = "Введите год рождения родственника")]
        public List<DateTime> RelBirhday { get; set; }

        [Required(ErrorMessage = "Введите ИНН паспорта")]
        public string PassportINN { get; set; }
        [Required(ErrorMessage = "Введите дату выдачи")]
        public DateTime PassportDateIn { get; set; }
        [Required(ErrorMessage = "Введите дату окончания")]
        public DateTime PassportDateOut { get; set; }
        [Required(ErrorMessage = "Введите кем выдан паспорт")]
        public string ByWhomGiven { get; set; }

        [Required(ErrorMessage = "Выберите пол")]
        public bool isGender { get; set; }
        [Required(ErrorMessage = "Не выбрано")]
        public bool isMilitaryService { get; set; }
        public IFormFile EmployeePhoto { get; set; }
        [Required(ErrorMessage = "Не выбрано")]
        public bool isMarried { get; set; }
        [Required(ErrorMessage = "Заполните адрес проживания")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Введите телефон")]
        public IEnumerable<string> Telephone { get; set; }
        [Required(ErrorMessage = "Введите почту")]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", ErrorMessage = "Введите коректную почту")]
        public IEnumerable<string> Email { get; set; }


        public List<DocumentViewModel> Documents { get; set; }
        [Required(ErrorMessage = "Введите название документа")]
        public List<string> DocTitle { get; set; }
        [Required(ErrorMessage = "Выберите файл")]
        public List<IFormFile> DocFile { get; set; }
        [Range(0, 100000, ErrorMessage = "Срок не может быть меньше 0")]
        public List<int> DocumentValidity { get; set; }
        [Required(ErrorMessage = "Укажите начальную дату")]
        public List<DateTime> StartDateDoc { get; set; }
        public List<DateTime?> EndDateDoc { get; set; }

        public List<CertificateViewModel> Certificates { get; set; }
        [Required(ErrorMessage = "Введите название сертификата")]
        public List<string> CerTitle { get; set; }
        [Required(ErrorMessage = "Выберите файл")]
        public List<IFormFile> CerFile { get; set; }
        [Range(0, 100000, ErrorMessage = "Срок не может быть меньше 0")]
        public List<int> CertificateValidity { get; set; }
        [Required(ErrorMessage = "Укажите начальную дату")]
        public List<DateTime> StartDateCer { get; set; }
        public List<DateTime?> EndDateCer { get; set; }

        public string Status { get; set; }
        public bool Notification { get; set; }

        public int DepartmentId { get; set; }
        public int PositionId { get; set; }

        public List<SkillViewModel> Skills { get; set; }
    }
}

HRSystem/Controllers/EmployeerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using HRSystem.Models;
using HRSystem.Repositories;
using HRSystem.ViewModels;
using Microsoft.AspNetCore.Http.Internal;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using System.IO;
using System.Net.Mime;
using System.Text.RegularExpressions;
using HRSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;

namespace HRSystem.Controllers
{
    public enum Status
    {
        AtWork,
        Dismissed,
        OnVacation
    }
    [Authorize(Roles = "Admin, User")]
    public class EmployeerController : Controller
    {
        private readonly IEmployeerRepository employeerRepository;
        private readonly IDepartmentRepository departmentRepository;
        private readonly IPositionRepository positionRepository;
        private readonly IPosReqRepository posReqRepository;
        private readonly IRelationRepository relationRepository;
        private readonly ISkillRepository skillRepository;
        private readonly IDocumentRepository documentRepository;
        private readonly ICertificateRepository certificateRepository;
        private readonly ISampleFormRepository sampleFormRepository;
        private readonly EmailSender emailSender;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IRequirementRepository requirementRepository;

        public EmployeerController(
            IEmployeerRepository employeerRepository,
            IDepartmentRepository departmentRepository,
            IPositionRepository positionRepository,
            IPosReqRepository posReqRepository,
            IRelationRepository relationRepository,
            ISkillRepository skillRepository,
            IDocumentRepository documentRepository,
            ICertificateRepository certificateRepository,
            ISampleFormRepository sampleFormRepository,
            EmailSender emailSender, UserManager<User> userManager, SignInManager<User> signInManager,
            IRequirementRepository requirementRepository)
        {
            this.employeerRepository = employeerRepository;
            this.departmentRepository = departmentRepository;
            this.positionRepository = positionRepository;
            this.posReqRepository = posReqRepository;
            this.relationRepository = relationRepository;
            this.skillRepository = skillRepository;
            this.documentRepository = documentRepository;
            this.certificateRepository = certificateRepository;
            this.sampleFormRepository = sampleFormRepository;
            this.emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            this.requirementRepository = requirementRepository;
        }

        public IActionResult Index(List<string> requirements)
        {
            var model = skillRepository.FilterByRequirements(requirements);
            ViewBag.Department = departmentRepository.GetAllEntities().ToList();
            ViewBag.Positions = positionRepository.GetAllEntities().ToList();
            ViewBag.Requirement = requirementRepository.GetAllEntities();
            ViewBag.Search = requirements;
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Department = departmentRepository.GetAllEntities().ToList();
            return View();
        }

        public IActionResult PosList(int id, int positionId)
        {
            id = -1 == id ? departmentRepository.GetFirst().Id : id;
            ViewBag.Positions = positionRepository.GetDepartmentPositions(id).ToList();
            ViewBag.Id = positionId;
            return PartialView();
        }

        public IActionResult SkillList(int positionId, int departmentId, int employeerId)
        {
            positionId = -1 == positionId ? positionRepository.GetFirst().Id : positionId;
            if (departmentId != 0)
            {
                try
                {
                    Position position = positionRepository.GetDepartmentPositions(departmentId).First();
                    positionId = position.Id;
                }
                catch (InvalidOperationException ex)
                {
                    Console.WriteLine(ex);
                    positionId = 0;
                }


            }
            ViewBag.Requirements = posReqRepository.FindPositionRequirements(positionId, employeerId);
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeerViewModel model)
        {
            Employeer employeer = employeerRepository.AddEmployeer(model);


            relationRepository.AddRangeRelations(model.RelName, model.RelType, model.RelBirhday, employeer.Id);
            skillRepository.AddRangeSkills(model.Skills, employeer.Id);
            documentRepository.AddDocuments(model.DocTitle, model.DocFile, employeer.Id, model.StartDateDoc, model.EndDateDoc);
            certificateRepository.AddCertificates(model.CerTitle, model.CerFile, employeer.Id, model.StartDateCer, model.EndDateCer);

            

            var users = new User { UserName = model.Email.First(), Email = model.Email.First() };
            string usersPWD = SendLoginAndPassword(employeer.Id);
            var createuser = await _userManager.CreateAsync(users, usersPWD);
            var user = await _userManager.FindByNameAsync(users.UserName);
            employeer.IdForPersonal = user.Id;
            if (createuser.Succeeded)
            {
                await _userManager.AddToRoleAsync(users, "User");              
            }
          


            return RedirectToAction("EmployeerInfo", new { id = employeer.Id });
        }

        public IActionResult EmployeerInfo(int id)
        {
            var model = new InfoViewModel()
            {
                Employeer = employeerRepository.GetEntityById(id),
                Relations = relationRepository.GetRelationsByEmployeerId(id).ToList(),
                Certificates = certificateRepository.GetCertificatesByEmployeerId(id).ToList(),
                Documents = documentRepository.GetDocumentsByEmploueerId(id),
                Requirements = skillRepository.GetSkillsByEmployeerId(id).ToList(),
                SampleForms = sampleFormRepository.GetAllEntities().ToList()
            };
            return View(model);
        }

        public IActionResult EmployeerShortInfo(int id)
        {
            return PartialView(employeerRepository.GetEntityById(id));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                employeerRepository.RemoveEntity(id);

            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User, Admin")]
        public IActionResult UpdatePesonalInfo(int id)
        {
            EmployeerViewModel model = employeerRepository.GetViewModel(id);
            ViewBag.Department = departmentRepository.GetAllEntities().ToList();
            return View(model);
        }
        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult UpdatePesonalInfo(EmployeerViewModel model)
        {
            employeerRepository.UpdateEmployeerViewModel(model);
            return RedirectToAction("EmployeerInfo", new { id = model.Id });
        }
        [Authorize(Roles = "User, Admin")]
        public string GetInfo(int id)
        {
            Employeer employeer = employeerRepository.GetEntityById(id);
            return JsonConvert.SerializeObject(string.Join("#", employeer.Telephone, employeer.Email),
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        //public string GetCerInfo(int id)
        //{
        //    string cer = certificateRepository.GetArray(id);
        //    return JsonConvert.SerializeObject(cer,
        //        new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        //}

        //public string GetDocInfo(int id)
        //{
        //    string cer = documentRepository.GetArray(id);
        //    return JsonConvert.SerializeObject(cer,
        //        new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        //}
        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public string ChangeAvatar(int id)
        {
            string path = employeerRepository.SaveImage(Request.Form.Files.First(), id);
            return JsonConvert.SerializeObject(path,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }


        [Authorize(Roles = "Admin")]
        public IActionResult UpdatePosition(int id, int departmentId, int positionId)
        {
            ViewBag.Department = departmentRepository.GetAllEntities().ToList();
            return View(new EmployeerViewModel()
            {
                Id = id,
                DepartmentId = departmentId,
                PositionId = positionId
            });
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdatePosition(EmployeerViewModel model)
        {
            employeerRepository.UpdatePosition(model.DepartmentId, model.PositionId, model.Id);
            skillRepository.UpdateSkills(model.Skills, model.Id);

            return RedirectToAction("EmployeerInfo", new { id = model.Id });
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]

HRSystem/Views/Employeer/Index.cshtml
@model IEnumerable<HRSystem.Models.Employeer>


@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Сотрудники</h1>

<div class="row">
@if (Context.User.IsInRole("Admin"))
{
    <div class="btn-group col-md-push-8  col-md-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Поиск по компетенциям</button>
    </div>
    <div class="btn-group col-md-push-8 col-md-2">
        <button class="btn btn-default btn-block" onclick="createEmp(@ViewBag.Department.Count, @ViewBag.Positions.Count)">Добавить</button>
    </div>
}
</div>
<br/>
<table id="employeerTable" class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ФИО</th>
        <th>Возраст</th>
        <th>Отдел</th>
        <th>Должность</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var emp in Model)
    {
        <tr>
            <td><a href="#" onclick="getModal(@emp.Id)">@string.Join(" ", emp.Surname, emp.Name)</a></td>
            <td>@{
                    int b = emp.BirthdayDate.Year ;
                    int a = DateTime.Now.Year - b;
                    <p>@a лет</p>
                }</td>
            <td>@emp.Department.Name</td>
            <td>@emp.Position.Name</td>
            <td>@switch (emp.Status)
                {
                    case "AtWork":<p>Работает</p>
                        break;
                    case "Dismissed":<p>На отпуске</p>
                        break;
                    case "OnVacation":<p>Не работает</p>
                        break;
                }</td>
        </tr>
    }
    </tbody>
</table>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <form asp-action="Index" asp-controller="Employeer">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Поиск по компетенциям</h4>
                </div>
                <div class="modal-body">

                    <div class="row">
                        @foreach (var req in ViewBag.Requirement)
                        {
                            <div class="col-lg-6" style="margin-bottom: 10px;">
                                @if (ViewBag.Search.Contains(req.Name))
                                {
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="requirements" value="@req.Name" checked="checked">
                                        </span>
                                        <span class="form-control text-center">@req.Name</span>
                                    </div>
                                }
                                else
                                {
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="requirements" value="@req.Name">
                                        </span>
                                        <span class="form-control text-center">@req.Name</span>
                                    </div>
                                }

                            </div>
                        }
                    </div>

                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-default" value="Поиск">
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="modalResult">
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function getModal(id) {
            $("#modalResult").load('@Url.Action("EmployeerShortInfo", "Employeer")?id=' + id);
            $("#myModal").modal();
        }
        function createEmp(department, position) {
            if (department === 0 || position === 0) {
                alert("Сначало создайте отдел и должность!");
            }
            else {
                document.location.replace('@Url.Action("Create", "Employeer")');
            }
        }
    </script>
} 

HRSystem/Views/Employeer/PosList.cshtml
@model HRSystem.ViewModels.EmployeerViewModel

<div class="form-group">
    <label asp-for="PositionId" class="control-label">Должность</label>
    <select asp-for="PositionId" class="form-control" id="position">
        @foreach (var p in ViewBag.Positions)
        {
            if (p.Id == ViewBag.Id)
            {
                <option value="@p.Id" id="@p.Id" selected="selected">@p.Name</option>
            }
            else
            {
                <option value="@p.Id" id="@p.Id">@p.Name</option>
            }
        }
    </select>
</div>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

HRSystem/Views/Employeer/UpdatePesonalInfo.cshtml
@model HRSystem.ViewModels.EmployeerViewModel

@{
    ViewData["Title"] = "UpdatePesonalInfo";
}

<h2>Изменение личных данных</h2>

<hr />
<div class="row">
        <form asp-action="UpdatePesonalInfo" method="post" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">Имя</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Surname" class="control-label">Фамилия</label>
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label">Отчество</label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label" asp-for="BirthdayDate">Дата рождения</label>
                        <input class="form-control" asp-for="BirthdayDate" type="date" />
                        <span asp-validation-for="BirthdayDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label" asp-for="Address">Адрес</label>
                        <input class="form-control" asp-for="Address" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="genderResult">
                        <div class="form-group">
                            <label asp-for="isMilitaryService" class="control-label">Военная служба</label>
                            <div class="radio">
                                <label>
                                    <input type="radio" asp-for="isMilitaryService" value="@true"> Служил
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" asp-for="isMilitaryService" value="@false"> Не служил
                                </label>
                            </div>
                            <span asp-validation-for="isMilitaryService" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="isMarried">Семейное положение</label>
                        <div class="radio">
                            <label>
                                <input type="radio" asp-for="isMarried" value="@true"> Женат
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" asp-for="isMarried" value="@false"> Холост
                            </label>
                        </div>
                        <span asp-validation-for="isMarried" class="text-danger"></span>
                    </div>
                    <label asp-for="Telephone">Телефон</label>
                    <div id="input_fields_wrap">
                        <div class="form-inline">
                            <div class="form-group">
                                <input class="phone form-control" asp-for="Telephone" type="text" id="tel_0" />
                            </div>
                            <button class="btn btn-default" id="add_field_button">+</button>
                            <span asp-validation-for="Telephone" class="text-danger"></span>
                        </div>
                    </div>
                    <label asp-for="Email">Почта</label>
                    <div class="input_email_wrap">
                        <div class="form-inline">
                            <div class="form-group">
                                <input class="form-control" asp-for="Email" type="text" id="email_0" />
                            </div>
                            <button class="btn btn-default" id="add_email_button">+</button>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group text-center" style="margin-top: 15px">
                        <input type="submit" value="Сохранить" class="btn btn-info" />
                    </div>
                </div>
        </form>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {

            $('#tel').val('');
            $('#em').val('');
            $.ajax
            ({
                type: "GET",

                url: '@Url.Action("GetInfo", "Employeer")',

                data: { 'id': @Model.Id },

                success: function(data) {
                    var answer = JSON.parse(data);
                    var array = answer.split('#');
                    var sum = 0;
                    $.each(array[0].split(','),
                        function (index, value) {
                            $('#tel_' + index + ':text').val(value);
                            $("#input_fields_wrap").append('<div class="form-inline"><input class="phone form-control" type="text" id="tel_' + (index + 1) + '" name="Telephone" value=""><a href="#" class="remove_field">Удалить</a><span class="text-danger field-validation-valid" data-valmsg-for="Telephone" data-valmsg-replace="true"></span></div>');
                            sum = index;
                        });
                    $('#tel_' + (sum + 1)).parent().remove();

                    $.each(array[1].split(','),
                        function (index, value) {
                            $('#email_' + index + ':text').val(value);
                            $(".input_email_wrap").append('<div class="form-inline"><input class="form-control" type="text" id="email_'+ (index + 1) +'" name="Email" value><a href="#" class="remove_email">Удалить</a><span class="text-danger field-validation-valid" data-valmsg-for="Email" data-valmsg-replace="true"></span></div>');
                            sum = index;
                        });
                    $('#email_' + (sum + 1)).parent().remove();



                },
                error : function(data) {
                    alert(data);
                }

                });

            initMask();
        });

    </script>

}

HRSystem/Views/Employeer/UpdatePosition.cshtml
@model HRSystem.ViewModels.EmployeerViewModel

@{
    ViewData["Title"] = "UpdatePosition";
}

<br/>
<div class="row">
    <div class="col-md-12">
        <form asp-action="UpdatePosition" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label">Отдел</label>
                <select asp-for="DepartmentId" class="form-control" id="department">
                    @foreach (var d in ViewBag.Department)
                    {
                        if (Model.DepartmentId == d.Id)
                        {
                            <option id="@d.Id" value="@d.Id" class="form-control" selecred="selected">@d.Name</option>
                        }
                        else
                        {
                            <option id="@d.Id" value="@d.Id" class="form-control">@d.Name</option>
                        }
                    }
                </select>
            </div>
            <div id="result">

            </div>
            <div id="result2" class="row">

            </div>
            <div class="form-group text-center" style="margin-top: 15px">
                <input type="submit" value="Сохранить" class="btn btn-info" />
            </div>
        </form>
    </div>

</div>
@section Scripts{ 
    <script>
        var emploueerId = @Model.Id;
        $(document).ready(function () {
            emploueerId = @Model.Id;
            var id = @Model.DepartmentId;
            var positionId = @Model.PositionId;
            $("#result").load('@Url.Action("PosList", "Employeer")?id=' + id + '&positionId=' + positionId);
            $("#result2").load('@Url.Action("SkillList", "Employeer")?positionId=' + positionId + '&employeerId=' + emploueerId);

        });


        $("select#department").change(
            function () {
                var id = $(this).children(":selected").attr("id");
                $("#result").load('@Url.Action("PosList", "Employeer")?id=' + id);
                $("#result2").load('@Url.Action("SkillList", "Employeer")?departmentId=' + id + '&employeerId=' + emploueerId);
            });

        var positionId = -1;
        $(document).change(function (e) {
            e.preventDefault();
            var selectBox = document.getElementById("position");
            var selectedValue = selectBox.options[selectBox.selectedIndex].value;
            if (selectedValue != positionId) {
                $("#result2").load('@Url.Action("SkillList", "Employeer")?positionId=' + selectedValue + '&employeerId=' + emploueerId);
            }
            positionId = selectedValue;
        });
    </script>
}